Задача 1

Подбрасываются три игральных кубика. Оцените вероятность того, что сумма значений этих кубиков не будет превышать 6.

Подсказка: оценкой вероятности может служить, например, относительная частота при большом числе опытов. Попробуйте реализовать наибольшее число опытов, которое позволяют ваш компьютер и/или ваше терпение.

Замечание: вообще в этом курсе мы не используем такие численные методы оценки вероятностей, и в будущем мы не будем их применять. Но тут сделаем исключение один раз.

In [16]:
import numpy as np

n - количество испытаний
a,b,c - подбрасывания кубиков

In [36]:
n = 50000000
a = np.random.randint(1,7, size=n)
b = np.random.randint(1,7, size=n)
c = np.random.randint(1,7, size=n)
print(a)
print(b)
print(c)

[3 1 1 ... 5 5 4]
[3 6 6 ... 5 1 3]
[3 2 3 ... 6 3 6]


Относительная частота случайного события — это отношение количества испытаний, в которых данное событие состоялось, к общему числу испытаний:
W(A)=m/n

𝑚  — число испытаний, в результате которых произошло событие  𝐴 ,
m = ((a+b+c) <=6).sum()
𝑛  — общее число испытаний

In [37]:
m = ((a+b+c) <=6).sum()
m

4628866

In [38]:
W = m/n
print(W)

0.09257732


Задача 2

Имеется колода в 52 карты. Найти число возможностей вытянуть из неё 4 карты так, чтобы среди них был хотя бы один туз.


In [22]:
def combinations(n: int, k: int) -> int:
    """Число сочетаний.
    """
    
    return np.math.factorial(n) // (np.math.factorial(k) * np.math.factorial(n - k))

a - число возможностей вытянуть из колоды в 52 карты 4 карты так, чтобы среди них был бы один туз

In [23]:
a = combinations(4,1)*combinations(48,3)
print(a)

69184


b - число возможностей вытянуть из колоды в 52 карты 4 карты так, чтобы среди них были 2 туза

In [24]:
b = combinations(4,2)*combinations(48,2)
print(b)

6768


In [ ]:
c - число возможностей вытянуть из колоды в 52 карты 4 карты так, чтобы среди них были 3 туза

In [25]:
c = combinations(4,3)*combinations(48,1)
print(c)

192


d - число возможностей вытянуть из колоды в 52 карты 4 карты так, чтобы среди них были 4 туза

In [26]:
d = combinations(4,4)*combinations(48,0)
print(d)

1


In [ ]:
Итого число возможностей вытянуть из неё 4 карты так, чтобы среди них был хотя бы один туз n:

In [27]:
n = a+b+c+d
print(n)

76145


Задача 3

Из 60 вопросов, входящих в экзаменационные билеты, студент знает 50. Случайным образом студент вытягивает 3 вопроса. Какова вероятность, что все выбранные вопросы знакомы студенту? Какова вероятность, что студент знает 2 вопроса из 3?



Количество случаев, при которых студент вытягивает 3 вопроса, которые знает

In [31]:
a = combinations(50,3)*combinations(10,0)
print(a)

19600


Количество комбинаций вытягивания 3 билетов из 60

In [32]:
n = combinations(60,3)
print(n)

34220


Вероятность, что все выбранные вопросы знакомы студенту

In [33]:
W=a/n
print(W)

0.5727644652250146


In [ ]:
Вероятность, что студент знает 2 вопроса из 3

In [34]:
W = combinations(50,2)*combinations(10,1)/combinations(60,3)
print(W)

0.35797779076563413


Задача 4

Бросается игральная кость. Пусть событие A - появление чётного числа, событие B - появление числа больше трёх. Являются ли эти события независимыми? Почему?



События  𝐴  и  𝐵  называются независимыми, если  𝑃(𝐴|𝐵)=𝑃(𝐴) , т.е. если наступление события  𝐵  не влияет на вероятность события  𝐴 , и наоборот.

P(A) = P(B) = 3/6 = 1/2
P(А|B) = 2/3 (четные числа больше 3 - это 4 и 6) 
Делаем вывод, что так как одно условие повлияло на вероятность другого, соответственно события являются зависимыми

Задача 5

Допустим, имеется некоторая очень редкая болезнь (поражает 0.1% населения). Вы приходите к врачу, вам делают тест на эту болезнь, и тест оказывается положительным. Врач говорит вам, что этот тест верно выявляет 99% больных этой болезнью и всего лишь в 1% случаев даёт ложный положительный ответ. Какова вероятность, что вы действительно больны ей?

Подсказка: используйте формулу Байеса с раскрытием знаменателя с помощью формулы полной вероятности.

__Формула Байеса__ позволяет «развернуть» условную вероятность $P(A|B)$, т.е. выразить её через $P(B|A)$. По определению условной вероятности:
$$P(A|B) = \dfrac{P(AB)}{P(B)}$$


А - факт болезни
B - положительный результат теста
P(A) - вероятность поражения болезнью =0,001
P(B) - полная вероятность положительного результата теста
P(B|A) - вероятность правильного результата теста = 0,99
W = P(A|B) - искомая величина - вероятность того, что пациент с положительным тестом действительно болен

P(АВ) = P(B|A) * P(A) =  0,99*0,001 = 0,00099

P(B) = 0.99*0.001+0.01*0.999

In [43]:
W = (0.99*0.001)/(0.99*0.001+0.01*0.999)
print(W)

0.09016393442622951
